[project]
name = "test-containers-github-actions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest==8.0.0",
    "redis==5.0.1",
    "testcontainers==3.7.1",
]
